name: Build iOS

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-13

    steps:
    - name: Checkout source
      uses: actions/checkout@v2

    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.19.0'

    - name: Install dependencies
      run: flutter pub get

    - name: Build iOS archive
      run: |
        flutter build ipa --no-codesign

    - name: Upload IPA Artifact
      uses: actions/upload-artifact@v3
      with:
        name: iOS-IPA
        path: build/ios/ipa/*.ipa
