name: Build iOS

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest

    steps:
    - name: Checkout source
      uses: actions/checkout@v2

    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.19.0'

    - name: Install dependencies
      run: flutter pub get

    - name: Build iOS app
      run: flutter build ios --release --no-codesign

    - name: Archive app
      run: |
        mkdir build_output
        cp -r build/ios/iphoneos/Runner.app build_output/
        cd build_output && zip -r Runner.zip Runner.app

    - name: Upload Artifact
      uses: actions/upload-artifact@v2
      with:
        name: iOS-App
        path: build_output/Runner.zip
